config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    get :join, to: 'events#join', as: 'join'
    get :accept_request, to: 'events#accept_request', as: 'accept_request'
    get  :reject_request, to: 'events#reject_request', as: 'reject_request'
  end

  get 'tags/:tag', to: 'events#index', as: :tag

  root to: "events#index"

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  include Workflow
    workflow_column :state
    workflow do
       state :request_sent do
         event :accept, transitions_to: :accepted
         event :reject, transitions_to: :rejected
       end
       state :accepted
       state :rejected
    end

  belongs_to :event
  belongs_to :user

  def self.join_event(user_id, event_id, state)
    self.create(user_id: user_id, event_id: event_id, state: state)
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :organizers, class_name: "User"
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :attendances
  has_many :users, through: :attendances

  def all_tags=(names)
    self.tags = names.split(",").map do |t|
      Tag.where(name: t.strip).first_or_create!
    end
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).events
  end

  def all_tags
    tags.pluck(:name).join(",")
  end

  def self.tag_counts
    Tag.select("tags.name, count(taggings.tag_id) as count").joins(:taggings).group("tags.name")
  end

  def self.event_owner(organizer_id)
    User.find_by(id: organizer_id)
  end

  def self.pending_requests(event_id)
    Attendance.where(event_id: event_id, state: 'request_sent')
  end
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"
  has_many :attendances
  has_many :events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :accept_request, :reject_request]
  before_filter :authenticate_user!
  before_action :event_owner!, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event_owners = @event.organizers
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join
    @attendance = Attendance.join_event(current_user.id, params[:event_id], 'request_sent')
   'Request Sent' if @attendance.save
   redirect_to events_path
  end

  def accept_request
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.accept!
    'Applicant Accepted' if @attendance.save
      respond_with(@attendance)
  end

   def reject_request
    @attendance = Attendance.where(params[:attendance_id]) rescue nil
    @attendance.reject!
    @attendance.save
   end


  private
    # Use callbacks to share common setup or constraints between actions.

    def event_owner!
      authenticate_user!
      if @event.organizer_id != current_user.id
        redirect_to events_path
        flash[:notice] = "You lack permission to do this."
      end
    end

    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :location, :agenda, :address, :organizer_id, :all_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :agenda %><br>
    <%= f.text_area :agenda %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :organizer_id %><br>
    <%= f.number_field :organizer_id %>
  </div>
  <div class="field">
    <%= f.label :all_tags, "Tags (separated by a comma.)" %></br>
    <%= f.text_field :all_tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organizer</th>
      <th>Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= l(event.start_date, format: :date_format) %></td>
        <td><%= l(event.end_date, format: :date_format) %></td>
        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= event.organizer_id %></td>
        <td>
            <% event.all_tags.split(',').each do |t| %>
            <%= link_to t, tag_path(t) %>
            <% end %>
        </td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-lg-4">
  <h3>Search Tags</h3>
  <div>
    <% tag_cloud Event.tag_counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
</div>

<br>


<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @event.agenda %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @event.organizer_id %>
</p>

<label>Organized By:</label><br/>
<%= @event_owner%>

<br/>

<p>
  <strong>Tags: </strong>
  <%= @event.all_tags %>
</p>

<% if user_signed_in? && @event.organizer_id == current_user.id %>
  <label>Join Requests</label>
  <% if @pending_requests.present? %>
    <% @pending_requests.each do |p| %>
      <%= p.user.email %>
      <%= link_to 'Accept', event_accept_request_path(event_id: @event.id, attendance_id: p.id), class: "btn btn-success btn-small" %>
      <%= link_to 'Reject', event_reject_request_path(event_id: @event.id, attendance_id: p.id), class: "btn btn-danger btn-small" %>
    <% end %>
  <% else %>
    <p>No Pending Requests for This Event</p>
  <% end %>
<% end %>




<%= link_to "Join", event_join_path(event_id: @event.id), class: "btn btn-success btn-small" %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>